### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by henryProductions0** [Vno12/Fix-Build-Physic-Engine#1]
![image](https://github.com/Vno12/Fix-Build-Physic-Engine/assets/115906994/2bd59101-6671-4438-a7b4-39f0c517e85f)

**Comment by henryProductions0** [comment]
i only tried to compile it

**Comment by c4ther** [comment]
install old libraries to compile kade engine

**Comment by c4ther** [comment]
should help

**Comment by henryProductions0** [comment]
@Vno12 
Compiling group: haxe
cl.exe -Iinclude -ID:/Nova pasta/Fix Build/.haxelib/discord_rpc/git/linc/ -ID:/Nova pasta/Fix Build/.haxelib/linc_luajit/git//linc/ -nologo -DHX_WINDOWS -GR -O2(optim-std) -Zi(debug) -FdD:\Nova pasta\Fix Build\export\release\windows\obj\obj/msvc64-nc/vc.pdb(debug) -Od(debug) -O2(release) -Os(optim-size) -Oy- -c -EHs -GS- -ID:/Nova pasta/Fix Build/.haxelib/hxcpp/4,3,2/include -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_CHECK_POINTER(haxe) -DHXCPP_STACK_LINE(haxe) -DHX_SMART_STRINGS(haxe) -DHXCPP_API_LEVEL=400(haxe) -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN(main) -wd4996 ... tags=[haxe,static]
 - src/openfl/display/_internal/Context3DElementType.cpp
 - src/sys/io/_Process/Stdout.cpp
 - src/flixel/input/actions/_FlxSteamController/FlxSteamControllerMetadata.cpp
Process creation failure : cl.exe

**Comment by henryProductions0** [comment]
@Vno12
